---
- name: nginx insallation
  
  connection: local
  become: yes
  tasks: 
    - name: insall nginx
      ansible.builtin.package:
          name: nginx
          state: present
    - name: start nginx service
      ansible.builtin.service:
         name: nginx
         state: started
         enabled: yes
